# Generated by Django 4.0.4 on 2022-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='empresa',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
