# Generated by Django 4.0.4 on 2022-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='empresa',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
