# Generated by Django 4.0.4 on 2022-05-07 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='opcao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='questao',
        ),
        migrations.RenameField(
            model_name='opcao',
            old_name='opcao_texto',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='votos',
        ),
        migrations.AddField(
            model_name='opcao',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='questoes',
            field=models.ManyToManyField(through='loja.QuestaoDoProduto', to='loja.questao'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='questao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loja.questao'),
        ),
        migrations.DeleteModel(
            name='OpcaoDaQuestaoProd',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='cart',
            name='produtos',
            field=models.ManyToManyField(to='loja.opcao'),
        ),
    ]
