# Generated by Django 4.0.4 on 2022-05-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_vendedor_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='empresa',
        ),
    ]
