# Generated by Django 4.0.4 on 2022-05-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_cart_remove_pedido_cliente_remove_pedido_opcao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
