# Generated by Django 4.0.3 on 2022-05-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_delete_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='produtos',
            field=models.ManyToManyField(to='loja.produto'),
        ),
    ]
