# Generated by Django 4.0.4 on 2022-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produtocarrinho_opcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocarrinho',
            name='opcs',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProdutoFinal',
        ),
    ]
