# Generated by Django 4.0.4 on 2022-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produtocarrinho_opcs_delete_produtofinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocarrinho',
            name='opcs',
            field=models.CharField(default='Não existe Personalização para este produto', max_length=100),
        ),
    ]
